name: Change indentation to tabs

on:
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config filter.tabindent.smudge 'unexpand --tabs=4 --first-only'
          git config filter.tabindent.clean 'unexpand --tabs=4 --first-only'
          git config user.name Markus-Rost
          git config user.email 37275477+Markus-Rost@users.noreply.github.com
          git add .
          git commit -m "Change indentation to tabs"
          git push
